//! Generates the hex neighbor-offset constant tables from the single canonical source,
//! `src/core/neighbor-dirs.json` (shared with the JS config in `src/core/config.js`). This keeps
//! the Rust engine and the JS renderer/input code reading the SAME 12 offsets — a mismatch would
//! silently change the simulation. The emitted file is `include!`d by `src/lib.rs`; the drift-guard
//! test `neighbor_dirs_match_canonical` (in lib.rs) pins the generated consts to the canonical
//! values as a backstop against any bug in the tiny scanner below.
//!
//! Dependency-free by design (build-dependencies would show in Cargo.lock and slow CI): the JSON
//! schema is fixed and simple, so we just scan every signed-integer token in document order. The
//! file holds `odd_r` (6 pairs) then `even_r` (6 pairs) = 24 integers; anything else panics the
//! build rather than emitting a wrong table.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // CARGO_MANIFEST_DIR is the crate root (hexlife-wasm/); the shared source lives one level up.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let src_path = Path::new(&manifest_dir).join("../src/core/neighbor-dirs.json");

    println!("cargo:rerun-if-changed={}", src_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let json = fs::read_to_string(&src_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", src_path.display()));

    // Split on the two keys so we can scan each table's integers independently and assert on shape.
    // This also guards against ordering/typo drift in the JSON (each half must yield exactly 12).
    let odd = scan_ints(section(&json, "odd_r", "even_r"));
    let even = scan_ints(section(&json, "even_r", ""));

    assert_eq!(odd.len(), 12, "neighbor-dirs.json odd_r must hold 6 [dc,dr] pairs (12 ints)");
    assert_eq!(even.len(), 12, "neighbor-dirs.json even_r must hold 6 [dc,dr] pairs (12 ints)");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("neighbor_dirs.rs");
    let generated = format!(
        "// @generated by build.rs from src/core/neighbor-dirs.json — do not edit.\n\
         const NEIGHBOR_DIRS_ODD_R: [[i32; 2]; 6] = {};\n\
         const NEIGHBOR_DIRS_EVEN_R: [[i32; 2]; 6] = {};\n",
        format_table(&odd),
        format_table(&even),
    );
    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

/// Return the substring of `json` starting at the `start` key up to (but excluding) the `end` key.
/// An empty `end` means "to the end of the string".
fn section<'a>(json: &'a str, start: &str, end: &str) -> &'a str {
    let from = json
        .find(start)
        .unwrap_or_else(|| panic!("neighbor-dirs.json missing key \"{start}\""))
        + start.len();
    let rest = &json[from..];
    if end.is_empty() {
        rest
    } else {
        let to = rest
            .find(end)
            .unwrap_or_else(|| panic!("neighbor-dirs.json missing key \"{end}\" after \"{start}\""));
        &rest[..to]
    }
}

/// Collect every signed-integer token (`-?\d+`) in `s`, in order.
fn scan_ints(s: &str) -> Vec<i32> {
    let mut out = Vec::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let c = bytes[i];
        let is_start = c.is_ascii_digit()
            || (c == b'-' && i + 1 < bytes.len() && bytes[i + 1].is_ascii_digit());
        if is_start {
            let begin = i;
            if c == b'-' {
                i += 1;
            }
            while i < bytes.len() && bytes[i].is_ascii_digit() {
                i += 1;
            }
            let token = &s[begin..i];
            out.push(token.parse::<i32>().expect("neighbor-dirs.json integer out of i32 range"));
        } else {
            i += 1;
        }
    }
    out
}

/// Format a flat list of 12 ints as a Rust `[[i32; 2]; 6]` literal.
fn format_table(ints: &[i32]) -> String {
    let pairs: Vec<String> = ints
        .chunks(2)
        .map(|p| format!("[{}, {}]", p[0], p[1]))
        .collect();
    format!("[{}]", pairs.join(", "))
}
