[package]
name = "hexlife-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # Specifies a dynamic library for WASM

[dependencies]
wasm-bindgen = "0.2" # The core dependency for JS interop