/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_worldsolid_free: (a: number, b: number) => void;
export const worldsolid_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const worldsolid_layerPtr: (a: number) => number;
export const worldsolid_pushLayer: (a: number) => [number, number];
export const worldsolid_finalizeVolume: (a: number, b: number) => [number, number];
export const worldsolid_rows: (a: number) => number;
export const worldsolid_columns: (a: number) => number;
export const worldsolid_numCells: (a: number) => number;
export const worldsolid_ticks: (a: number) => number;
export const worldsolid_subLayers: (a: number) => number;
export const worldsolid_basePlate: (a: number) => number;
export const worldsolid_solidStates: (a: number) => number;
export const worldsolid_totalLayers: (a: number) => number;
export const worldsolid_volumeBytes: (a: number) => number;
export const worldsolid_pushedLayers: (a: number) => number;
export const worldsolid_isFinalized: (a: number) => number;
export const worldsolid_neighborOf: (a: number, b: number, c: number) => [number, number, number];
export const worldsolid_componentCount: (a: number) => number;
export const worldsolid_keptComponents: (a: number) => number;
export const worldsolid_keptVoxels: (a: number) => number;
export const worldsolid_droppedVoxels: (a: number) => number;
export const worldsolid_floating: (a: number) => number;
export const worldsolid_buildMesh: (a: number, b: number) => [number, number];
export const worldsolid_triangleCount: (a: number) => number;
export const worldsolid_vertexCount: (a: number) => number;
export const worldsolid_serializeMesh: (a: number, b: number, c: number, d: number) => [number, number];
export const worldsolid_meshPtr: (a: number) => number;
export const worldsolid_meshLen: (a: number) => number;
export const worldsolid_volumeChecksum: (a: number) => number;
export const worldsolid_voxelAt: (a: number, b: number, c: number) => [number, number, number];
export const solid_engine_version: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
